foggyline_catalog:
    resource: "@FoggylineCatalogBundle/Controller/"
    type:     annotation
    prefix:   /catalog/

foggyline_catalog_category:
    resource: "@FoggylineCatalogBundle/Controller/CategoryController.php"
    type: annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
